### ISSUE TITLE
chrome-http?

### ISSUE THREAD

**Issue by beriberikix** [feross/chrome-net#10]
I was looking for a Browserify lib for chrome apps that implements `http` and stumbled onto your project. Is that something you are planning or have you seen something comparable?

**Comment by rynomad** [comment]
I know this issue is closed, but I thought y'all might still be interested: I've got a working [http-chrome] (https://github.com/rynomad/http-chrome) module up. It's a direct copy of the node core module, with some slight modifications made by the build script to replace 'net' with 'chrome-net' and remove some V8 calls. It works well enough that I was able to get the express powered [federated wiki](https://github.com/rynomad/wiki-chrome) server running functionally with a little bit of hacking (mostly working around other modules that use eval, which chrome hates).

This would have been impossible if not for the work here in chrome-net, so I figured I'd send a ping :)

**Comment by feross** [comment]
Nice work @rynomad! You can add a mention at the end of the readme if you want!
