### ISSUE TITLE
Could not load extension from ''. Manifest file is missing or unreadable.

### ISSUE THREAD

**Issue by dzlab** [feross/chrome-net#4]
I got this error when running `npm test` after step **ok 23 Clean browserify build** on linux/chromium

**Comment by elenkadelf** [comment]
Good afternoon, I am testing various projects with Argent X StarkNet Wallet and encountered the following error when loading an older version of Wallet 
~\Desktop\argent-extension-v2.3.0
Error
Manifest file is missing or unreadable
Manifest could not be loaded.
I need to install the old version based on your instructions, because now I don't know how it will affect my participation in various projects with the change of the old address to the new one
